- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r path/to/requirements.txt  # Adjust the path if needed
  displayName: 'Install dependencies'
